## Data Analyst

- SQL
- Developer - MNC
- Power BI - Charts (Visually)
- Insights - Charts
- One shot Query


## Data Scientist 

- Excel
- Python - numpy, pandas
- Scale - Millions of rows
- Scikit - Data prediction
- Matplot, seaborn - Charts - (Rapid prototyping)
- Line by line (Step)


## Numpy

- Working with arrays (1D)
- Performant (compared Python List)
- C language
- Statistical oriented - mean, median, mode

In [3]:
import numpy as np

In [1]:
marks1 =  [90, 80, 20, 40]

print(marks1 * 2) # repeat operator

[90, 80, 20, 40, 90, 80, 20, 40]


In [4]:
marks2 = np.array([90, 80, 20, 40]) # array: List -> Array

print(marks2 * 2)  # Catering - Data Scientist

[180 160  40  80]


## Python way to double the list

In [ ]:
marks_dbl = [mark * 2 for mark in marks1] 

marks_dbl

In [5]:
np.ones(100)
np.ones(10) # Identity matrix

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10)

In [ ]:
# Array of 20 5's

In [6]:
fives = np.ones(20) * 5

fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [7]:
np.arange(10) # 0 -> 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Task: 1 -> 10
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Task: Odd number
# array([1, 3, 5, 7, 9])
# Clue: skip

np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## Operation
- Multiply, Division, Addition, Subtraction
- Boolean (matrix/ mask)

In [ ]:
np.arange(1, 11) * 2

In [ ]:
np.arange(1, 11) / 2

In [ ]:
np.arange(1, 11) + 2

In [10]:
np.arange(1, 11) - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.arange(1, 11) + np.arange(1, 11)  # Matrix Addition

### Operations between two arrays

In [ ]:
np.array([9, 2, 3]) + np.array([1, 2, 5])  # Stats

In [ ]:
np.array([9, 2, 3]) - np.array([6, 2, 5]) 

In [ ]:
np.array([9, 2, 3]) ** np.array([3, 2, 5]) # 9^3, 2^2, 3^5

In [ ]:
np.array([9, 2, 3]) / np.array([3, 2, 5])

In [ ]:
# np.array([9, 2, 3]) - np.array([6, 2, 5, 7])  # Different size -> error

In [ ]:
[9, 2, 3] + [1, 2, 5]

### Boolean (matrix/ mask)

In [11]:
np.arange(1, 11) > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
first_ten_nums = np.arange(1, 11)
only_five_bm =  first_ten_nums > 5
first_ten_nums[only_five_bm]

In [ ]:
first_ten_nums = np.arange(1, 11)
first_ten_nums[first_ten_nums > 5]

In [12]:
nums = np.array([5, 6, 6, 7, 8, 9, 10, 2, 5, 1])
# bm = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) > 5
bm = np.array([True, False, True, False, False,  True,  True,  True,  True, True])
# array([False, False, False, False, False,  True,  True,  True,  True, True])
print(nums[bm])

[ 5  6  9 10  2  5  1]


In [ ]:
# Task 1.1
# 1-200 only even numbers | With skip of arange

In [ ]:
even_nums = np.arange(2, 201, 2)

even_nums

In [ ]:
# Task 1.2
# 1-200 only even numbers | Dont use skip of arange
# Clue: %

In [ ]:
nums = np.arange(1, 201)
bm = nums % 2 == 0
nums[bm]

In [ ]:
nums = np.arange(1, 201)
nums[nums % 2 == 0]

In [ ]:
ages = np.random.randint(18, 60, 5)
ages_list  = ages.tolist()

print(ages_list)

In [ ]:
ages = np.random.randint(18, 60, 50)  # Random data generator

print(ages)
ages[ages > 25]

In [77]:
ages = np.random.randint(18, 60, 1_000_000)
ages_list  = ages.tolist()

In [78]:
%%time
ages_list = [age *2 for age in ages_list]

CPU times: total: 46.9 ms
Wall time: 49.7 ms


In [79]:
ages = np.random.randint(18, 60, 1_000_000)

In [80]:
%%time
ages * 2

CPU times: total: 0 ns
Wall time: 2.55 ms


array([ 48,  66, 102, ...,  74,  60,  72], shape=(1000000,), dtype=int32)

## Performance

- Numpy arrays are 100-1000 times the performance of python list
- %%time - time operation

## Statistical oriented - mean, mode, median, std

- mean -> Average
- mode -> The most repeated number (most popular)
- median -> The middle number (when sorted)
- standard deviation -> Average distance between the mean and numbers

In [18]:
marks = np.random.randint(40, 100, 11)

print(marks)
print(marks.mean())
print(np.mean(marks))

[40 42 96 45 45 89 56 64 66 87 70]
63.63636363636363
63.63636363636363


In [19]:
print(np.median(marks))

64.0


In [20]:
print(np.sum(marks))

700


In [21]:
print(np.std(marks))

19.21776038068918


In [29]:
sixty_fours = np.ones(10) * 64

print(sixty_fours)
np.mean(sixty_fours)

[64. 64. 64. 64. 64. 64. 64. 64. 64. 64.]


np.float64(64.0)

In [ ]:
np.std(sixty_fours) # Spread of the values / Distribution

np.float64(0.0)

### Task
- investment ->  R1_000
- rate_of_interest -> 5%
- At the end of 2years. What is the balance? 
  - 1st year R50   -> 1_050
  - 2nd year R52.5 -> 1_102.5

### Task 1
At the every year tell me balance for 10 years
Clue: General formula
1102.5 -> 1000 + 
[1050, 1102.5 ...., ]


### Task 2
At the year of ten years what will be the balance
Clue: Slicing


### Task 3
How is much % its increase as compared to initial investment


In [44]:
investment = 1_000
interest_rate = 1.05
num_years = np.arange(1, 11)

# print(investment * interest_rate ** 3)
# print( (interest_rate **  num_years))
# print( investment * (interest_rate **  num_years))

balance_over_years = investment * interest_rate **  num_years

balance_over_years

array([1050.        , 1102.5       , 1157.625     , 1215.50625   ,
       1276.2815625 , 1340.09564063, 1407.10042266, 1477.45544379,
       1551.32821598, 1628.89462678])

### Slicing
- Index
- Negative Index
- Range

In [46]:
balance_over_years[1]
balance_over_years[1:4]

array([1102.5    , 1157.625  , 1215.50625])

In [ ]:
### Task 2

balance_over_years[9]
balance_over_years[-1]

np.float64(1628.894626777442)

In [50]:
### Task 3

current_balance = balance_over_years[-1]
profit = (current_balance - investment) / investment

print(profit * 100)


62.8894626777442


## Useful methods
- max, min - argmax, argmin
- unique, flip
- String methods

In [51]:
salaries = np.random.randint(1_000, 10_000, 10)

salaries

array([3571, 4609, 7264, 4381, 9364, 9360, 8609, 2575, 3472, 9986],
      dtype=int32)

In [52]:
np.max(salaries)

np.int32(9986)

In [53]:
np.min(salaries)

np.int32(2575)

In [56]:
print(np.argmax(salaries))

9


In [57]:
print(np.argmin(salaries))

7


In [58]:
nums =  np.random.randint(1, 4, 10)

nums

array([3, 1, 2, 3, 3, 1, 1, 3, 3, 2], dtype=int32)

In [59]:
unique_nums = np.unique(nums)

unique_nums

array([1, 2, 3], dtype=int32)

In [ ]:
np.flip(unique_nums) # reverse the array

array([3, 2, 1], dtype=int32)

## Task 1

hourly_visitors = [468, 279,  73, 272 ,406 ,128 ,302 ,216, 140, 82]

- 1.1 Total visitors in the day?
- 1.2 Which is the peak hour?
- 1.3 On average how many people visit per hour

### Output
```
Total visitors in the day: 2366
Peak hour: 1
Average people visit: 237
```

In [67]:
hourly_visitors = np.array([468, 279,  73, 272 ,406 ,128 ,302 ,216, 140, 82])

print(f"Total visitors in the day: {np.sum(hourly_visitors)}")
print(f"Peak hour: {np.argmax(hourly_visitors) + 1}")
print(f"Average people visit: {round(np.mean(hourly_visitors))}")

Total visitors in the day: 2366
Peak hour: 1
Average people visit: 237


In [68]:
hourly_visitors = np.array([468, 279,  73, 272 ,406 ,128 ,302 ,216, 140, 82])

print(f"""
Total visitors in the day: {np.sum(hourly_visitors)}
Peak hour: {np.argmax(hourly_visitors) + 1}
Average people visit: {round(np.mean(hourly_visitors))}
""")


Total visitors in the day: 2366
Peak hour: 1
Average people visit: 237



In [72]:
words = np.array(["hello", "world", "numpy"])

print(np.char.upper(words))
print(np.char.capitalize(words))

['HELLO' 'WORLD' 'NUMPY']
['Hello' 'World' 'Numpy']


## Task 2
Normalize the Array:

- 2.1 Trim leading and trailing spaces.
- 2.2 Convert all items to lowercase.
- 2.3 Ensure there are no duplicate items in the array.

In [81]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])

items_strip = np.char.strip(items)
items_lower = np.char.lower(items_strip)

np.unique(items_lower)

array(['apple', 'banana', 'blueberry', 'cucumber', 'grape', 'kiwi',
       'lemon', 'mango', 'orange', 'pineapple', 'raspberry', 'tomato'],
      dtype='<U10')

## Task 3 (Challenging)
Filtering Operations:
- 3.1 Find and display all items that start with the letter 'b'.
    - `['banana', 'blueberry']`
- 3.2 Find and display all items that contain the letter 'e' exactly once. 
   - `['apple', 'cucumber', 'grape', 'lemon', 'orange', 'raspberry']`

In [87]:
# 3.1 - startswith

print(items_lower)
b_word_bm = np.char.startswith(items_lower, 'b')
print(b_word_bm)
items_lower[b_word_bm]

['apple' 'banana' 'grape' 'cucumber' 'pineapple' 'tomato' 'orange'
 'orange' 'lemon' 'kiwi' 'mango' 'blueberry' 'raspberry']
[False  True False False False False False False False False False  True
 False]


array(['banana', 'blueberry'], dtype='<U10')

In [86]:
items_lower[np.char.startswith(items_lower, 'b')]

array(['banana', 'blueberry'], dtype='<U10')

In [91]:
# 3.2 - count

items_lower[np.char.count(items_lower, 'e') == 1]

array(['apple', 'grape', 'cucumber', 'orange', 'orange', 'lemon',
       'raspberry'], dtype='<U10')

In [95]:
items_lower.shape

(13,)

## 2D Matrix / Arrays

In [92]:
num_3x3 = np.array([[1, 3, 4],
                    [6, 10, 77],  
                    [9, 20, 24]  
                    ])

In [93]:
num_3x3

array([[ 1,  3,  4],
       [ 6, 10, 77],
       [ 9, 20, 24]])

In [94]:
num_3x3.shape

(3, 3)

In [96]:
num_3x3 * 2

array([[  2,   6,   8],
       [ 12,  20, 154],
       [ 18,  40,  48]])

In [97]:
num_3x3 / 2

array([[ 0.5,  1.5,  2. ],
       [ 3. ,  5. , 38.5],
       [ 4.5, 10. , 12. ]])

In [98]:
num_3x3 - 2

array([[-1,  1,  2],
       [ 4,  8, 75],
       [ 7, 18, 22]])