## Data Analyst

- SQL
- Developer - MNC
- Power BI - Charts (Visually)
- Insights - Charts
- One shot Query


## Data Scientist 

- Excel
- Python - numpy, pandas
- Scale - Millions of rows
- Scikit - Data prediction
- Matplot, seaborn - Charts - (Rapid prototyping)
- Line by line (Step)


## Numpy

- Working with arrays (1D)
- Performant (compared Python List)
- C language
- Statistical oriented - mean, median, mode

In [3]:
import numpy as np

In [2]:
marks1 =  [90, 80, 20, 40]

print(marks1 * 2) # repeat operator

[90, 80, 20, 40, 90, 80, 20, 40]


In [ ]:
marks2 = np.array([90, 80, 20, 40]) # array: List -> Array

print(marks2 * 2)  # Catering - Data Scientist

[180 160  40  80]


## Python way to double the list

In [ ]:
marks_dbl = [mark * 2 for mark in marks1]

marks_dbl

[180, 160, 40, 80]

In [8]:
np.ones(100)
np.ones(10) # Identity matrix

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Array of 20 5's

In [10]:
fives = np.ones(20) * 5

fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [ ]:
np.arange(10) # 0 -> 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Task: 1 -> 10
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Task: Odd number
# array([1, 3, 5, 7, 9])
# Clue: skip

np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## Operation
- Multiply, Division, Addition, Subtraction
- Boolean (matrix/ mask)

In [15]:
np.arange(1, 11) * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
np.arange(1, 11) / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [17]:
np.arange(1, 11) + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
np.arange(1, 11) - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.arange(1, 11) + np.arange(1, 11)  # Matrix Addition

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Operations between two arrays

In [ ]:
np.array([9, 2, 3]) + np.array([1, 2, 5])  # Stats

array([10,  4,  8])

In [ ]:
np.array([9, 2, 3]) - np.array([6, 2, 5])

array([ 3,  0, -2])

In [ ]:
np.array([9, 2, 3]) ** np.array([3, 2, 5]) # 9^3, 2^2, 3^5

array([729,   4, 243])

In [41]:
np.array([9, 2, 3]) / np.array([3, 2, 5])

array([3. , 1. , 0.6])

In [ ]:
# np.array([9, 2, 3]) - np.array([6, 2, 5, 7])  # Different size -> error

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [21]:
[9, 2, 3] + [1, 2, 5]

[9, 2, 3, 1, 2, 5]

### Boolean (matrix/ mask)

In [22]:
np.arange(1, 11) > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
first_ten_nums = np.arange(1, 11)
only_five_bm =  first_ten_nums > 5
first_ten_nums[only_five_bm]

array([ 6,  7,  8,  9, 10])

In [25]:
first_ten_nums = np.arange(1, 11)
first_ten_nums[first_ten_nums > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
nums = np.array([5, 6, 6, 7, 8, 9, 10, 2, 5, 1])
# bm = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) > 5
bm = np.array([True, False, True, False, False,  True,  True,  True,  True, True])
# array([False, False, False, False, False,  True,  True,  True,  True, True])
print(nums[bm])
bm

[ 6  6  7  8  9 10]


In [ ]:
# Task 1.1
# 1-200 only even numbers | With skip of arange

In [45]:
even_nums = np.arange(2, 201, 2)

even_nums

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [ ]:
# Task 1.2
# 1-200 only even numbers | Dont use skip of arange
# Clue: %

In [ ]:
nums = np.arange(1, 201)
bm = nums % 2 == 0
nums[bm]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [49]:
nums = np.arange(1, 201)
nums[nums % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [58]:
ages = np.random.randint(18, 60, 5)
ages_list  = ages.tolist()

print(ages_list)

[28, 42, 38, 19, 22]


In [ ]:
ages = np.random.randint(18, 60, 50)  # Random data generator

print(ages)
ages[ages > 25]

[32 35 34 51 28 37 40 24 44 28 18 23 34 50 48 33 34 50 40 57 28 22 23 18
 29 27 41 44 52 57 51 54 41 21 48 52 30 20 53 57 27 53 48 24 24 25 33 20
 44 31]


array([32, 35, 34, 51, 28, 37, 40, 44, 28, 34, 50, 48, 33, 34, 50, 40, 57,
       28, 29, 27, 41, 44, 52, 57, 51, 54, 41, 48, 52, 30, 53, 57, 27, 53,
       48, 33, 44, 31], dtype=int32)

In [9]:
ages = np.random.randint(18, 60, 500_000)
ages_list  = ages.tolist()

print(ages_list)

[42, 24, 30, 32, 36, 59, 38, 35, 48, 41, 38, 51, 37, 20, 41, 48, 32, 23, 41, 32, 59, 30, 56, 29, 35, 37, 18, 29, 31, 41, 41, 52, 45, 58, 31, 49, 31, 28, 36, 59, 33, 39, 45, 31, 28, 22, 42, 52, 53, 49, 59, 25, 45, 29, 23, 54, 53, 35, 59, 28, 44, 29, 51, 40, 46, 30, 27, 52, 37, 42, 30, 51, 34, 22, 34, 33, 54, 35, 23, 36, 35, 42, 53, 35, 28, 23, 38, 54, 50, 25, 29, 42, 26, 24, 29, 28, 37, 57, 20, 33, 52, 57, 31, 22, 36, 31, 34, 43, 56, 23, 27, 46, 38, 50, 40, 39, 33, 56, 28, 19, 20, 42, 34, 22, 51, 43, 54, 53, 43, 41, 57, 18, 38, 30, 39, 43, 36, 34, 19, 52, 47, 43, 20, 48, 53, 32, 55, 56, 42, 57, 39, 26, 40, 56, 41, 53, 20, 46, 29, 51, 26, 39, 36, 29, 54, 24, 51, 29, 43, 48, 51, 59, 48, 32, 25, 49, 33, 19, 37, 28, 20, 42, 21, 40, 41, 28, 18, 23, 21, 34, 54, 35, 56, 39, 25, 34, 35, 25, 28, 42, 38, 55, 38, 27, 43, 38, 45, 24, 40, 33, 40, 32, 42, 44, 33, 58, 29, 20, 39, 59, 59, 28, 50, 24, 25, 39, 41, 37, 45, 22, 59, 51, 54, 42, 41, 34, 18, 45, 38, 35, 59, 58, 54, 18, 48, 41, 46, 56, 52, 38,

In [10]:
%%time
ages_list = [age *2 for age in ages_list]
print(ages_list)

[84, 48, 60, 64, 72, 118, 76, 70, 96, 82, 76, 102, 74, 40, 82, 96, 64, 46, 82, 64, 118, 60, 112, 58, 70, 74, 36, 58, 62, 82, 82, 104, 90, 116, 62, 98, 62, 56, 72, 118, 66, 78, 90, 62, 56, 44, 84, 104, 106, 98, 118, 50, 90, 58, 46, 108, 106, 70, 118, 56, 88, 58, 102, 80, 92, 60, 54, 104, 74, 84, 60, 102, 68, 44, 68, 66, 108, 70, 46, 72, 70, 84, 106, 70, 56, 46, 76, 108, 100, 50, 58, 84, 52, 48, 58, 56, 74, 114, 40, 66, 104, 114, 62, 44, 72, 62, 68, 86, 112, 46, 54, 92, 76, 100, 80, 78, 66, 112, 56, 38, 40, 84, 68, 44, 102, 86, 108, 106, 86, 82, 114, 36, 76, 60, 78, 86, 72, 68, 38, 104, 94, 86, 40, 96, 106, 64, 110, 112, 84, 114, 78, 52, 80, 112, 82, 106, 40, 92, 58, 102, 52, 78, 72, 58, 108, 48, 102, 58, 86, 96, 102, 118, 96, 64, 50, 98, 66, 38, 74, 56, 40, 84, 42, 80, 82, 56, 36, 46, 42, 68, 108, 70, 112, 78, 50, 68, 70, 50, 56, 84, 76, 110, 76, 54, 86, 76, 90, 48, 80, 66, 80, 64, 84, 88, 66, 116, 58, 40, 78, 118, 118, 56, 100, 48, 50, 78, 82, 74, 90, 44, 118, 102, 108, 84, 82, 68, 36,

In [11]:
%%time
ages * 2

CPU times: total: 0 ns
Wall time: 1 ms


array([84, 48, 60, ..., 40, 74, 54], shape=(500000,), dtype=int32)

## Statistical Oriented
- mean -> Average
- median -> most repeated number
- median -> middle number (when sorted)

In [12]:
marks = np.random.randint(40, 100, 11)
print(marks.mean())
print(np.mean(marks))

64.54545454545455
64.54545454545455


In [ ]:
print(np.median(marks))

73.0


In [14]:
print(np.sum(marks))

710


In [15]:
print(np.std(marks))

19.378355481232788


### Task 1
At the every year tell me balance for 10 years
Clue: General formula
1102.5 -> 1000 +
[1050, 1102.5 ...., ]

In [ ]:
INTEREST_RATE = 0.05
amount = 1_000

amt_list = []

for i in range(10):
    amount *= (1 + INTEREST_RATE)
    amt_list.append(round(amount, 2))

print(amt_list)

year_10 = round(amt_list[9] * 1.05, 2)
print(year_10)


[1050.0, 1102.5, 1157.62, 1215.51, 1276.28, 1340.1, 1407.1, 1477.46, 1551.33, 1628.89]
1710.33


In [ ]:
investment = 1_000
interest_rate = 1.05
num_years = np.arange(1, 11)

print(investment * interest_rate ** num_years)

year_10_interest = investment * interest_rate ** num_years[-1]

print(year_10_interest)

[1050.         1102.5        1157.625      1215.50625    1276.2815625
 1340.09564063 1407.10042266 1477.45544379 1551.32821598 1628.89462678]
1628.894626777442


### Slicing
- Index
- Negative Index
- Range