In [3]:
marks1 = [90, 80, 20, 40]

print([mark * 2 for mark in marks1])

[180, 160, 40, 80]


In [2]:
import numpy as np

marks2 = np.array([90, 80, 20, 40])

print(marks2 * 2)

[180 160  40  80]


In [4]:
5 * np.ones(20)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Task: Odd number
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## Operation
- Multiply, Division, Addition, Subtraction
- Boolean (matrix / mask)

In [8]:
np.arange(1, 11) * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.arange(1, 11) / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [10]:
np.arange(1, 11) + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
np.arange(1, 11) - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [12]:
np.arange(1, 11) + np.arange(1, 11)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [46]:
np.array([9, 2, 3]) + np.array([1, 2, 5])

array([10,  4,  8])

In [ ]:
[9, 2, 3] + [1, 2, 5]

[9, 2, 3, 1, 2, 5, 6]

In [15]:
# Filtering
np.arange(1, 11) > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
first_ten_nums = np.arange(1, 11)
only_five_bm = first_ten_nums > 5
first_ten_nums[only_five_bm]

array([ 6,  7,  8,  9, 10])

In [ ]:
first_ten_nums = np.arange(1, 11)
first_ten_nums[first_ten_nums > 5]

array([ 6,  7,  8,  9, 10])

In [49]:
# Task 1.1
# 1-200 only even numbers | With skip of arange

even_num = np.arange(0, 201, 2)
even_num

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [52]:
# Task 1.2
# 1-200 only even numbers | Dont use skip of arange

even_num = np.arange(2, 201)
even_num[even_num % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [56]:
ages = np.random.randint(18, 60, 50)

ages[ages > 25]

array([48, 38, 28, 56, 35, 55, 53, 37, 42, 49, 43, 28, 51, 57, 34, 28, 54,
       55, 48, 49, 59, 51, 44, 40, 27, 55, 56, 58, 59, 54, 29, 49, 42, 59,
       47, 59, 57, 52, 51, 34], dtype=int32)