In [3]:
marks1 = [90, 80, 20, 40]

print([mark * 2 for mark in marks1])

[180, 160, 40, 80]


In [2]:
import numpy as np

marks2 = np.array([90, 80, 20, 40])

print(marks2 * 2)

[180 160  40  80]


In [4]:
5 * np.ones(20)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])